version: "3"

services:
  app:
    build:
      context: .
      dockerfile:
        ci/app/Dockerfile
    env_file:
      - ci/app/.env
    labels:
      NAME: "django_app"
    volumes:
      - app_static_volume:/opt/app/static
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    networks:
      - internal

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - app_static_volume:/home/app/web/static
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - internal
      - external_network

  postgres:
    build:
      context: .
      dockerfile:
        ci/postgres/Dockerfile
    env_file:
      - ci/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - $HOME/postgresql-compose-edition/data:/var/lib/postgresql/data
      - ./sqlite_to_postgres/movies_database.sql:/docker-entrypoint-initdb.d/movies_database.sql
    #      Не работает почему-то в контейнере такой запуск скрипта (вроде все по доке делал)
    networks:
      - internal
      - external_network

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    labels:
      NAME: 'api-swagger'
    ports:
      - "8080:8080"
    volumes:
      - ./postman/openapi.yaml:/swagger.yaml
    environment:
      - SWAGGER_JSON=/swagger.yaml
    depends_on:
      - app

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    labels:
      NAME: 'Elastic-search'
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
#     if low memory and cpu - use settings ES_JAVA_OPTS
#      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    depends_on:
      - postgres
    networks:
      - internal
      - external_network

  postgres-es-etl:
    build:
      context: .
      dockerfile:
        ci/etl_service/Dockerfile
    env_file:
      - ci/etl_service/.env
    labels:
      NAME: "etl_service"
    depends_on:
      - app
      - postgres
      - elastic
    networks:
      - internal

networks:
  external_network: { }
  internal:
    internal: true

volumes:
  app_static_volume: { }

