version: "3"

services:
  app:
    build:
      context: .
      dockerfile:
        ci/app/Dockerfile
    env_file:
      - ci/app/.env
    labels:
      NAME: "django_app"
    volumes:
      - app_static_volume:/opt/app/static
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    networks:
      - internal

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - app_static_volume:/home/app/web/static
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - internal
      - external

  postgres:
    build:
      context: .
      dockerfile:
        ci/postgres/Dockerfile
    env_file:
      - ci/postgres/.env
    ports:
      - "5435:5432"
    volumes:
      - $HOME/postgresql-compose-edition/data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  external:
    external:
      name: external_network
  internal:
    internal: true

volumes:
  app_static_volume: {}

